backend/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :scholarship_applications do
        post 'send_email', on: :collection, to: 'scholarship_applications#send_email', as: 'send_email'
      end
      post 'register', to: 'users#register', as: 'users_register'
      resources :users do
        get 'scholarship_applications', on: :member, to: 'users#scholarship_applications'
      end
      post 'login', to: 'users#login', as: 'users_login'
      post 'refresh', to: 'users#refresh', as: 'users_refresh'
      get 'verify_email/:token', to: 'users#verify', as: 'users_verify_email'
      post 'resend_verification', to: 'users#resend_verification', as: 'users_resend_verification'
      get 'check_token', to: 'users#check_token', as: 'users_check_token'
      post 'logout', to: 'users#logout', as: 'users_logout'
      resources :scholarships, only: [:index, :create, :show, :edit, :update, :destroy] do
        post 'upload', on: :collection
      end
      resources :survey_questions
      resources :subscribers do
        post 'soft_delete', on: :collection, to: 'subscribers#soft_del', as: 'soft_delete'
        post 'restore', on: :collection, to: 'subscribers#restore'
      end
      resources :scholarship_types
      resources :courses
      resources :survey_responses
      resources :newsletters
      resources :benefits
      resources :ph_addresses
      resources :benefit_categories
      resources :schools
      resources :scholarship_providers do
        get 'scholarships', on: :member, to: 'scholarship_providers#scholarships', as: 'scholarship_providers_scholarships'
        get 'scholarship_applications', on: :member, to: 'scholarship_providers#scholarship_applications'
        put 'scholarship_applications/:scholarship_application_id', on: :member, to: 'scholarship_providers#update_scholarship_application', as: 'scholarship_providers_update_scholarship_applications'
      end
      resources :scholarship_provider_profiles
      resources :regions
      resources :provinces
      resources :cities
      resources :roles
      resources :student_profiles
      resources :user_permissions
    end
  end
end

backend/app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  belongs_to :user

  default_scope -> { where(deleted_at: nil) }

  before_validation do
    self.age = ((Time.zone.now - self.user.birthdate.to_time) / 1.year.seconds).floor
  end

  def as_json(options = {})
    super(options.merge(except: [:created_at, :updated_at, :deleted_at]))
  end
end

backend/app/controllers/api/v1/student_profiles_controller.rb
module Api
  module V1
    class StudentProfilesController < ApplicationController
      skip_before_action :verify_authenticity_token
      rescue_from ActiveRecord::RecordNotFound, with: :skip_record_not_found
      before_action :authenticate_user, only: %i[ show create edit update destroy ]
      before_action :set_student_profile, only: %i[ show create edit update destroy ]
      
      # GET /student_profiles or /student_profiles.json
      def index
        @student_profiles = StudentProfile.includes(:user).all

        render json: @student_profiles
      end

      # GET /student_profiles/1 or /student_profiles/1.json
      def show
        render json: @student_profiles.as_json
      end

      # GET /student_profiles/new
      def new
        @student_profile = StudentProfile.new
      end

      # GET /student_profiles/1/edit
      def edit
      end

      # POST /student_profiles or /student_profiles.json
      def create
        if  @student_profile.present?
          if @student_profile.update(student_profile_params)
            if params[:birthdate].present?
              @user.update(birthdate: params[:birthdate])
            end
            render json: { message: 'Student profile updated successfully', profile: @student_profile, birthdate: @user.birthdate }, status: :ok
          else
            render json: @student_profile.errors, status: :unprocessable_entity
          end
        else
          student_profile = StudentProfile.new(student_profile_params)
          @user = User.find(params[:user_id])
          student_profile.user = @user
          
          if student_profile.save
            if params[:birthdate].present?
              @user.update(birthdate: params[:birthdate])
            end
            render json: {
              message: "Student details successfully saved.",
              profile: student_profile,
              birthdate: @user.birthdate
            }, status: :ok
          else
            render json: student_profile.errors, status: :unprocessable_entity
          end
        end
      end

      # PATCH/PUT /student_profiles/1 or /student_profiles/1.json
      def update
        if @student_profile.update(student_profile_params)
          render json: { message: 'Student profile updated successfully', profile: @student_profile }, status: :ok
        else
          render json: @student_profile.errors, status: :unprocessable_entity
        end
      end

      # DELETE /student_profiles/1 or /student_profiles/1.json
      def destroy
        @student_profile.destroy!

        respond_to do |format|
          format.html { redirect_to student_profiles_url, notice: "Student profile was successfully destroyed." }
          format.json { head :no_content }
        end
      end

      private
        def authenticate_user
          @user = User.find(params[:user_id])

          if @user.email_address != JwtService.decode(cookies[:email])['email']
            render_unauthorized_response
            return
          end
        end

        def skip_record_not_found
          # Do nothing or handle in a specific way if needed
        end

        # Use callbacks to share common setup or constraints between actions.
        def set_student_profile
          @student_profile = StudentProfile.find_by(user_id: params[:user_id])
        end

        # Only allow a list of trusted parameters through.
        def student_profile_params
          params.require(:student_profile).permit(
            :user_id,
            :about,
            :full_name,
            :birthdate,
            :email,
            :age,
            :nationality,
            :gender,
            :state,
            :secondary_school_name,
            :secondary_school_year,
            :secondary_school_address,
            :secondary_school_phone_number,
            :secondary_school_awards,
            :secondary_school_organizations,
            :elementary_school_name,
            :elementary_school_year,
            :elementary_school_address,
            :elementary_school_phone_number,
            :elementary_school_awards,
            :elementary_school_organizations,
            :guardian_full_name,
            :guardian_contact_number,
            :guardian_relationship,
            :avatar,
            :id
          )
        end
    end
  end
end

backend/app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

backend/app/views/student_profiles/_form.html.erb
<%= form_with(model: student_profile) do |form| %>
  <% if student_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_profile.errors.count, "error") %> prohibited this student_profile from being saved:</h2>

      <ul>
        <% student_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/student_profiles/_student_profile.html.erb
<div id="<%= dom_id student_profile %>">
</div>

backend/app/views/student_profiles/edit.html.erb
<h1>Editing student profile</h1>

<%= render "form", student_profile: @student_profile %>

<br>

<div>
  <%= link_to "Show this student profile", @student_profile %> |
  <%= link_to "Back to student profiles", student_profiles_path %>
</div>

backend/app/views/student_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student profiles</h1>

<div id="student_profiles">
  <% @student_profiles.each do |student_profile| %>
    <%= render student_profile %>
    <p>
      <%= link_to "Show this student profile", student_profile %>
    </p>
  <% end %>
</div>

<%= link_to "New student profile", new_student_profile_path %>

backend/app/views/student_profiles/new.html.erb
<h1>New student profile</h1>

<%= render "form", student_profile: @student_profile %>

<br>

<div>
  <%= link_to "Back to student profiles", student_profiles_path %>
</div>

backend/app/views/student_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_profile %>

<div>
  <%= link_to "Edit this student profile", edit_student_profile_path(@student_profile) %> |
  <%= link_to "Back to student profiles", student_profiles_path %>

  <%= button_to "Destroy this student profile", @student_profile, method: :delete %>
</div>