backend/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :scholarship_applications do
        post 'send_email', on: :collection, to: 'scholarship_applications#send_email', as: 'send_email'
      end
      post 'register', to: 'users#register', as: 'users_register'
      resources :users do
        get 'scholarship_applications', on: :member, to: 'users#scholarship_applications'
      end
      post 'login', to: 'users#login', as: 'users_login'
      post 'refresh', to: 'users#refresh', as: 'users_refresh'
      get 'verify_email/:token', to: 'users#verify', as: 'users_verify_email'
      post 'resend_verification', to: 'users#resend_verification', as: 'users_resend_verification'
      get 'check_token', to: 'users#check_token', as: 'users_check_token'
      post 'logout', to: 'users#logout', as: 'users_logout'
      resources :scholarships, only: [:index, :create, :show, :edit, :update, :destroy] do
        post 'upload', on: :collection
      end
      resources :survey_questions
      resources :subscribers do
        post 'soft_delete', on: :collection, to: 'subscribers#soft_del', as: 'soft_delete'
        post 'restore', on: :collection, to: 'subscribers#restore'
      end
      resources :scholarship_types
      resources :courses
      resources :survey_responses
      resources :newsletters
      resources :benefits
      resources :ph_addresses
      resources :benefit_categories
      resources :schools
      resources :scholarship_providers do
        get 'scholarships', on: :member, to: 'scholarship_providers#scholarships', as: 'scholarship_providers_scholarships'
        get 'scholarship_applications', on: :member, to: 'scholarship_providers#scholarship_applications'
        put 'scholarship_applications/:scholarship_application_id', on: :member, to: 'scholarship_providers#update_scholarship_application', as: 'scholarship_providers_update_scholarship_applications'
      end
      resources :scholarship_provider_profiles
      resources :regions
      resources :provinces
      resources :cities
      resources :roles
      resources :student_profiles
      resources :user_permissions
    end
  end
end

backend/app/controllers/api/v1/scholarship_types_controller.rb
module Api
  module V1
    class ScholarshipTypesController < ApplicationController
    before_action :set_scholarship_type, only: %i[ show edit update destroy ]

    # GET /scholarship_types or /scholarship_types.json
    def index
      @scholarship_types = ScholarshipType.all
      render json: @scholarship_types
    end

    # GET /scholarship_types/1 or /scholarship_types/1.json
    def show
    end

    # GET /scholarship_types/new
    def new
      @scholarship_type = ScholarshipType.new
    end

    # GET /scholarship_types/1/edit
    def edit
    end

    # POST /scholarship_types or /scholarship_types.json
    def create
      @scholarship_type = ScholarshipType.new(scholarship_type_params)

      respond_to do |format|
        if @scholarship_type.save
          format.html { redirect_to scholarship_type_url(@scholarship_type), notice: "Scholarship type was successfully created." }
          format.json { render :show, status: :created, location: @scholarship_type }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @scholarship_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /scholarship_types/1 or /scholarship_types/1.json
    def update
      respond_to do |format|
        if @scholarship_type.update(scholarship_type_params)
          format.html { redirect_to scholarship_type_url(@scholarship_type), notice: "Scholarship type was successfully updated." }
          format.json { render :show, status: :ok, location: @scholarship_type }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @scholarship_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /scholarship_types/1 or /scholarship_types/1.json
    def destroy
      @scholarship_type.destroy!

      respond_to do |format|
        format.html { redirect_to scholarship_types_url, notice: "Scholarship type was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_scholarship_type
        @scholarship_type = ScholarshipType.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def scholarship_type_params
        params.require(:scholarship_type).permit(:scholarship_type_name)
      end
    end
  end
end

backend/app/helpers/scholarship_types_helper.rb
module ScholarshipTypesHelper
end

backend/app/views/scholarship_types/_form.html.erb
<%= form_with(model: scholarship_type) do |form| %>
  <% if scholarship_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(scholarship_type.errors.count, "error") %> prohibited this scholarship_type from being saved:</h2>

      <ul>
        <% scholarship_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :scholarship_type_name, style: "display: block" %>
    <%= form.text_field :scholarship_type_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/scholarship_types/_scholarship_type.html.erb
<div id="<%= dom_id scholarship_type %>">
  <p>
    <strong>Scholarship type name:</strong>
    <%= scholarship_type.scholarship_type_name %>
  </p>

</div>

backend/app/views/scholarship_types/edit.html.erb
<h1>Editing scholarship type</h1>

<%= render "form", scholarship_type: @scholarship_type %>

<br>

<div>
  <%= link_to "Show this scholarship type", @scholarship_type %> |
  <%= link_to "Back to scholarship types", scholarship_types_path %>
</div>

backend/app/views/scholarship_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scholarship types</h1>

<div id="scholarship_types">
  <% @scholarship_types.each do |scholarship_type| %>
    <%= render scholarship_type %>
    <p>
      <%= link_to "Show this scholarship type", scholarship_type %>
    </p>
  <% end %>
</div>

<%= link_to "New scholarship type", new_scholarship_type_path %>

backend/app/views/scholarship_types/new.html.erb
<h1>New scholarship type</h1>

<%= render "form", scholarship_type: @scholarship_type %>

<br>

<div>
  <%= link_to "Back to scholarship types", scholarship_types_path %>
</div>

backend/app/views/scholarship_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @scholarship_type %>

<div>
  <%= link_to "Edit this scholarship type", edit_scholarship_type_path(@scholarship_type) %> |
  <%= link_to "Back to scholarship types", scholarship_types_path %>

  <%= button_to "Destroy this scholarship type", @scholarship_type, method: :delete %>
</div>