backend/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :scholarship_applications do
        post 'send_email', on: :collection, to: 'scholarship_applications#send_email', as: 'send_email'
      end
      post 'register', to: 'users#register', as: 'users_register'
      resources :users do
        get 'scholarship_applications', on: :member, to: 'users#scholarship_applications'
      end
      post 'login', to: 'users#login', as: 'users_login'
      post 'refresh', to: 'users#refresh', as: 'users_refresh'
      get 'verify_email/:token', to: 'users#verify', as: 'users_verify_email'
      post 'resend_verification', to: 'users#resend_verification', as: 'users_resend_verification'
      get 'check_token', to: 'users#check_token', as: 'users_check_token'
      post 'logout', to: 'users#logout', as: 'users_logout'
      resources :scholarships, only: [:index, :create, :show, :edit, :update, :destroy] do
        post 'upload', on: :collection
      end
      resources :survey_questions
      resources :subscribers do
        post 'soft_delete', on: :collection, to: 'subscribers#soft_del', as: 'soft_delete'
        post 'restore', on: :collection, to: 'subscribers#restore'
      end
      resources :scholarship_types
      resources :courses
      resources :survey_responses
      resources :newsletters
      resources :benefits
      resources :ph_addresses
      resources :benefit_categories
      resources :schools
      resources :scholarship_providers do
        get 'scholarships', on: :member, to: 'scholarship_providers#scholarships', as: 'scholarship_providers_scholarships'
        get 'scholarship_applications', on: :member, to: 'scholarship_providers#scholarship_applications'
        put 'scholarship_applications/:scholarship_application_id', on: :member, to: 'scholarship_providers#update_scholarship_application', as: 'scholarship_providers_update_scholarship_applications'
      end
      resources :scholarship_provider_profiles
      resources :regions
      resources :provinces
      resources :cities
      resources :roles
      resources :student_profiles
      resources :user_permissions
    end
  end
end

backend/app/models/benefit.rb
class Benefit < ApplicationRecord
  has_and_belongs_to_many :scholarships, join_table: "scholarship_benefits"

  default_scope -> { where(deleted_at: nil) }

  validates :benefit_name, presence: true
end

backend/app/controllers/api/v1/benefits_controller.rb
module Api
  module V1
    class BenefitsController < ApplicationController
      before_action :set_benefit, only: %i[ show edit update destroy ]
    
      # GET /benefits or /benefits.json
      def index
        @benefits = Benefit.all

        render json: @benefits
      end
    
      # GET /benefits/1 or /benefits/1.json
      def show
      end
    
      # GET /benefits/new
      def new
        @benefit = Benefit.new
      end
    
      # GET /benefits/1/edit
      def edit
      end
    
      # POST /benefits or /benefits.json
      def create
        @benefit = Benefit.new(benefit_params)
    
        respond_to do |format|
          if @benefit.save
            format.html { redirect_to benefit_url(@benefit), notice: "Benefit was successfully created." }
            format.json { render :show, status: :created, location: @benefit }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @benefit.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /benefits/1 or /benefits/1.json
      def update
        respond_to do |format|
          if @benefit.update(benefit_params)
            format.html { redirect_to benefit_url(@benefit), notice: "Benefit was successfully updated." }
            format.json { render :show, status: :ok, location: @benefit }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @benefit.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /benefits/1 or /benefits/1.json
      def destroy
        @benefit.destroy!
    
        respond_to do |format|
          format.html { redirect_to benefits_url, notice: "Benefit was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_benefit
          @benefit = Benefit.find(params[:id])
        end
    
        # Only allow a list of trusted parameters through.
        def benefit_params
          params.require(:benefit).permit(:benefit_name)
        end
    end
  end
end

backend/app/helpers/benefits_helper.rb
module BenefitsHelper
end

backend/app/views/benefits/_benefit.html.erb
<div id="<%= dom_id benefit %>">
  <p>
    <strong>Benefit name:</strong>
    <%= benefit.benefit_name %>
  </p>

</div>

backend/app/views/benefits/_form.html.erb
<%= form_with(model: benefit) do |form| %>
  <% if benefit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(benefit.errors.count, "error") %> prohibited this benefit from being saved:</h2>

      <ul>
        <% benefit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :benefit_name, style: "display: block" %>
    <%= form.text_field :benefit_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/benefits/edit.html.erb
<h1>Editing benefit</h1>

<%= render "form", benefit: @benefit %>

<br>

<div>
  <%= link_to "Show this benefit", @benefit %> |
  <%= link_to "Back to benefits", benefits_path %>
</div>

backend/app/views/benefits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Benefits</h1>

<div id="benefits">
  <% @benefits.each do |benefit| %>
    <%= render benefit %>
    <p>
      <%= link_to "Show this benefit", benefit %>
    </p>
  <% end %>
</div>

<%= link_to "New benefit", new_benefit_path %>

backend/app/views/benefits/new.html.erb
<h1>New benefit</h1>

<%= render "form", benefit: @benefit %>

<br>

<div>
  <%= link_to "Back to benefits", benefits_path %>
</div>

backend/app/views/benefits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @benefit %>

<div>
  <%= link_to "Edit this benefit", edit_benefit_path(@benefit) %> |
  <%= link_to "Back to benefits", benefits_path %>

  <%= button_to "Destroy this benefit", @benefit, method: :delete %>
</div>